#We chose an alpine machine
FROM python:alpine

#Labels
LABEL maintainers="ECE SimuSec"
LABEL BuildDate="16/11/21"

#We update it
RUN apk update
RUN apk add build-base libffi-dev libc-dev tk

#We install asyncua
RUN pip install --no-cache-dir asyncua
#RUN pip3 install --no-cache-dir tk

#Copy the script
#COPY server-minimal_generateur_0.1.0.py server-minimal_generateur_0.1.0.py
COPY certificates/ /certificates/
COPY . /

#Pass the power generated as an environment variable
ENV GENE=500

#Run it
##CMD ["python3", "-u", "server-minimal_generateur_0.1.0.py", "500"]
CMD ["sh","-c","python3 -u server-minimal_generateur_0.1.0.py $GENE"]

