#We chose an alpine machine
FROM python:alpine

#Labels
LABEL maintainers="ECE SimuSec"
LABEL BuildDate="16/11/21"

#We update it
RUN apk update
RUN apk add build-base libffi-dev libc-dev

#We install asyncua
RUN pip install --no-cache-dir asyncua

#Copy the script
COPY server-minimal_generateur_0.1.0.py server-minimal_generateur_0.1.0.py

#Run it
CMD ["python3", "-u", "server-minimal_generateur_0.1.0.py", "500"]