version: '3'

services:
  server-conso1:
    build: docker-server-minimal_consommateur/.
    image: server-conso1
    environment:
     - CONSO=250
    restart: always
    volumes:
     - '//var/run/docker.sock:/run/docker.sock'
     - certificates-volume:/certificates-all


  server-conso2:
    build: docker-server-minimal_consommateur/.
    image: server-conso2
    environment:
     - CONSO=300
    restart: always
    volumes:
     - '//var/run/docker.sock:/run/docker.sock'
     - certificates-volume:/certificates-all


  server-conso3:
    build: docker-server-minimal_consommateur/.
    image: server-conso3
    environment:
     - CONSO=350
    restart: always
    volumes:
     - '//var/run/docker.sock:/run/docker.sock'
     - certificates-volume:/certificates-all


  server-gene1:
    build: docker-server-minimal_generateur/.
    image: server-gene1
    ports:
     - "2222:22"
    environment:
     - GENE=800
     - COEFF=0.2
    restart: always
    volumes:
     - '//var/run/docker.sock:/run/docker.sock'
     - certificates-volume:/certificates-all


  server-gene2:
    build: docker-server-minimal_generateur/.
    image: server-gene2
    ports:
     - "2223:22"
    environment:
     - GENE=700
     - COEFF=0.3
    restart: always
    volumes:
     - '//var/run/docker.sock:/run/docker.sock'
     - certificates-volume:/certificates-all


  client-scada1:
    build: docker-client-minimal_scada/.
    image: client-scada1
    ports:
     - "5000:5000"
    environment:
     - NbConso=3
     - NbGene=2
    restart: always
    volumes:
     - '//var/run/docker.sock:/run/docker.sock'
     - certificates-volume:/certificates-all


  client-scada-rescue:
    build: docker-client-minimal_scada_rescue/.
    image: client-scada-rescue
    ports:
     - "5001:5000"
    environment:
     - NbConso=3
     - NbGene=2
    restart: always
    volumes:
     - '//var/run/docker.sock:/run/docker.sock'
     - certificates-volume:/certificates-all


volumes:
  certificates-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "certificates-all" 

