version: '3'

services:
  server-conso1:
    build: docker-server-minimal_consommateur/.
    image: server-conso1
    environment:
     - CONSO= 150
    restart: always


  server-gene1:
    build: docker-server-minimal_generateur/.
    image: server-gene1
    environment:
     - GENE= 500
    restart: always


  client_captor1:
    build: docker-client-minimal_captor/.
    image: client-captor1
    environment:
     - COUNT= 1
    restart: always
    volumes:
     - volume1:/data


  client_scada1:
    build: docker-client-minimal_scada/.
    image: client-scada1
    ports:
      - "5000:5000"
    environment:
     - NbConso= 1
     - NbGene= 1
    restart: always

  client_scada_rescue:
    build: docker-client-minimal_scada_rescue/.
    image: client-scada-rescue
    ports:
      - "5001:5001"
    environment:
     - NbConso= 1
     - NbGene= 1
    restart: always

volumes:
  volume1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/kali/PFE/data"
  volume2:


