version: '3'

services:
  server-conso1:
    build: docker-server-minimal_consommateur/.
    image: server-conso1
    environment:
     - CONSO=300
    restart: always
    volumes:
     - '/run/docker.sock:/run/docker.sock'
     - certificates-volume:/certificates-all

  server-gene1:
    build: docker-server-minimal_generateur/.
    image: server-gene1
    environment:
     - GENE=400
     - COEFF=0.1
    restart: always
    volumes:
     - '/run/docker.sock:/run/docker.sock'
     - certificates-volume:/certificates-all


  client-captor1:
    build: docker-client-minimal_captor/.
    image: client-captor1
    environment:
     - COUNT=1
    restart: always
    volumes:
     - '/run/docker.sock:/run/docker.sock'
     - certificates-volume:/certificates-all
     - volume1:/data


  client-scada1:
    build: docker-client-minimal_scada/.
    image: client-scada1
    ports:
     - "5000:5000"
     - "2222:22"
    environment:
     - NbConso=1
     - NbGene=1
    restart: always
    volumes:
     - '/run/docker.sock:/run/docker.sock'
     - certificates-volume:/certificates-all

  client-scada-rescue:
    build: docker-client-minimal_scada_rescue/.
    image: client-scada-rescue
    environment:
     - NbConso=1
     - NbGene=1
    restart: always
    volumes:
     - '/run/docker.sock:/run/docker.sock'
     - certificates-volume:/certificates-all


volumes:
  volume1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "data" 

  certificates-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "certificates-all" 

