version: '3'

services:
  server-conso1:
    build: docker-server-minimal_consommateur/.
    image: server-conso1
    environment:
     - CONSO=500
    restart: always
    volumes:
     - '/run/docker.sock:/run/docker.sock'
     - certificates-volume:/certificates-all


  server-conso2:
    build: docker-server-minimal_consommateur/.
    image: server-conso2
    environment:
     - CONSO=400
    restart: always
    volumes:
      - certificates-volume:/certificates-all

  server-conso3:
    build: docker-server-minimal_consommateur/.
    image: server-conso3
    environment:
     - CONSO= 350
    restart: always
    volumes:
      - certificates-volume:/certificates-all
    

  server-gene1:
    build: docker-server-minimal_generateur/.
    image: server-gene1
    environment:
     - GENE=800
     - COEFF=0.23
    restart: always
    volumes:
     - '/run/docker.sock:/run/docker.sock'
     - certificates-volume:/certificates-all


  server-gene2:
    build: docker-server-minimal_generateur/.
    image: server-gene2
    environment:
     - GENE=400
     - COEFF=0.15
    restart: always
    # volumes:
    #  - '/run/docker.sock:/run/docker.sock'
    #  - certificates-volume:/certificates-all


  server-gene2:
    build: docker-server-minimal_generateur/.
    image: server-gene2
    environment:
     - GENE= 450
    restart: always
    volumes:
      - certificates-volume:/certificates-all


  client-captor2:
    build: docker-client-minimal_captor/.
    image: client-captor2
    environment:
     - COUNT=2
    restart: always
    volumes:
     - '/run/docker.sock:/run/docker.sock'
     - certificates-volume:/certificates-all
     - volume1:/data


  client-scada1:
    build: docker-client-minimal_scada/.
    image: client-scada1
    ports:
     - "5000:5000"
     - "2222:22"
    environment:
     - NbConso= 3
     - NbGene= 2
    restart: always
    # volumes:
    #  - '/run/docker.sock:/run/docker.sock'
    #  - certificates-volume:/certificates-all


  client-scada-rescue:
    build: docker-client-minimal_scada_rescue/.
    image: client-scada-rescue
    ports:
     - "5001:5000"
     - "2223:22"
    environment:
     - NbConso=2
     - NbGene=2
    restart: always
    volumes:
     - '/run/docker.sock:/run/docker.sock'
     - certificates-volume:/certificates-all


volumes:
  volume1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "data" 

  volume2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "data"

  certificates-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "certificates-all" 

