#We chose an alpine machine
FROM python:alpine

#Labels
LABEL maintainers="ECE SimuSec"
LABEL BuildDate="16/11/21"

#We update it
RUN apk update
RUN apk add --no-cache build-base libffi-dev libc-dev curl

#We install asyncua
RUN pip install --no-cache-dir asyncua

#Copy the script
COPY . /

#Manage certificates
RUN mkdir /certificates-all
VOLUME /certificates-all

ENV COUNT=0

#Run it
CMD ["sh","-c","python3 -u client-minimal_capteur.py $COUNT"]
