#We chose an alpine machine
FROM python:alpine

#Labels
LABEL maintainers="ECE SimuSec"
LABEL BuildDate="16/11/21"

#We update it
RUN apk update
RUN apk add --no-cache build-base libffi-dev libc-dev

#We install asyncua
RUN pip install --no-cache-dir asyncua

#We install an SFTP-server and make it vulnerable
RUN apk add openssh && \
	ssh-keygen -A && \
	sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config && \
	echo -e "root\rroot" | passwd root

EXPOSE 22

#Copy the script
COPY ./requirements.txt /
RUN pip install -r requirements.txt

COPY . /

RUN apk add --no-cache openssl
RUN mkdir /certificates-all

VOLUME /certificates-all


#ENV COUNT
ENV NbConso=0
ENV NbGene=0

#Run it
CMD ["sh","-c","/usr/sbin/sshd && python3 -u clientminimalscada.py $NbConso $NbGene"]
