#We chose an alpine machine
FROM python:alpine

#Labels
LABEL maintainers="ECE SimuSec"
LABEL BuildDate="16/11/21"

#We update it
RUN apk update
RUN apk add build-base libffi-dev libc-dev

#We install asyncua
RUN pip install --no-cache-dir asyncua

#Copy the script
COPY . /

#Pass the consumption as an environment variable
ENV CONSO=0

#Run it
CMD ["sh","-c","python3 -u serveur-minimal_consommateur_0.1.py $CONSO"]

