#We chose an alpine machine
FROM python:alpine

#Labels
LABEL maintainers="ECE SimuSec"
LABEL BuildDate="16/11/21"

#We update it
RUN apk update
RUN apk add --no-cache build-base libffi-dev libc-dev tk

#We install asyncua
RUN pip install --no-cache-dir asyncua
#RUN pip3 install --no-cache-dir tk

#Copy the script
COPY . /

RUN apk add --no-cache openssl curl
RUN mkdir /certificates-all
#RUN openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -config configuration_certs.cnf -keyout certificates/privateKey.pem -out certificates/certificate.der

VOLUME /certificates-all


#Pass the power generated as an environment variable
ENV GENE=500
ENV COEFF=0.1

#Run it
CMD ["sh","-c","python3 -u server-minimal_generateur_0.1.0.py $GENE $COEFF"]

